<!-- R Commander Markdown Template -->

Replace with Main Title
=======================

### monte

### `r as.character(Sys.Date())`

```{r echo=FALSE}
# include this code chunk as-is to set options
knitr::opts_chunk$set(comment=NA, prompt=TRUE, out.width=750, fig.height=8, fig.width=8)
library(Rcmdr)
library(car)
library(RcmdrMisc)
```

```{r}
N=500
```


```{r}
n=20
```


```{r}
sample(N,n)
```


```{r}
TE=c(300,200,100)
```


```{r}
N=600
```


```{r}
n=30
```


```{r}
ni=n/N*TE; ni
```


```{r}
ni2=round(ni,0);ni2
```


```{r}
sample(TE[1],ni2[1])
```


```{r}
sample(TE[2],ni2[2])
```


```{r}
sample(TE[3],ni2[3])
```


```{r}
TE=c(300,200,100)
```


```{r}
N=600
```


```{r}
n=30
```


```{r}
ni=n/N*TE; ni
```


```{r}
ni2=round(ni,0);ni2
```


```{r}
teste=c(sample(TE[1],ni2[1]))
```


```{r}
sample(TE[2],ni2[2])
```


```{r}
sample(TE[3],ni2[3])
```


```{r}
teste
```


```{r}
TE=c(300,200,100)
```


```{r}
N=600
```


```{r}
n=30
```


```{r}
ni=n/N*TE; ni
```


```{r}
ni2=round(ni,0);ni2
```

```{r}
TE=c(300,200,100)
```


```{r}
N=600
```


```{r}
n=30
```


```{r}
ni=n/N*TE; ni
```


```{r}
ni2=round(ni,0);ni2
```


```{r}
total = c(sample(TE[1],ni2[1]),
sample(TE[2],ni2[2]),
sample(TE[3],ni2[3])
)
```


```{r}
TE=c(300,200,100)
```


```{r}
N=600
```


```{r}
n=30
```


```{r}
ni=n/N*TE; ni
```


```{r}
ni2=round(ni,0);ni2
```


```{r}
total = c(sample(TE[1],ni2[1]),sample(TE[2],ni2[2]),sample(TE[3],ni2[3]))
```


```{r}
TE=c(300,200,100)
```


```{r}
N=600
```


```{r}
n=30
```


```{r}
ni=n/N*TE; ni
```


```{r}
ni2=round(ni,0);ni2
```


```{r}
total = c(sample(TE[1],ni2[1]),sample(TE[2],ni2[2]),sample(TE[3],ni2[3]))
```


```{r}
total
```


```{r}
N = 1000
```


```{r}
n = 50
```


```{r}
r = round(N/n,0)
```


```{r}
r
```


```{r}
sort_elem1 = sample(r,1)
```


```{r}
sort_elem1
```


```{r}
posicao = seq(sort_elem1,N,r);
```


```{r}
posicao
```


